version: '3'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: image-backend 
    container_name: backend
    ports: 
      - "8000:8000"
    working_dir: /usr/src/app
    command: ["npm", "run", "start"]
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules


  frontend:
    build: 
        context: ./frontend
        dockerfile: Dockerfile
    image: image-frontend 
    container_name: frontend
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    command: ["npm", "start"]
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules